### ISSUE TITLE
Duplicate SIGABRT crash report

### ISSUE THREAD

**Issue by alexander-ivanoff** [getsentry/sentry-kotlin-multiplatform#247] opened 2024-08-01 01:20 UTC
### Platform

Apple

### Installed

CocoaPods

### Version

0.7.1

### Steps to Reproduce

Hello,
We are utilizing Kotlin Multiplatform Sentry in our project. A few weeks ago, we encountered an issue where our crash reports started duplicating. One report contains a legit kotlin stack trace, while the other is SIGABORT which includes a stack trace with coroutines machinery. The breadcrumbs in both reports are identical. 

I attached both stacktraces.

Could you please help us understand the possible cause of the report duplication?

[kotlin_crash.txt](https://github.com/user-attachments/files/16448552/kotlin_crash.txt)
[sigabrt_crash.txt](https://github.com/user-attachments/files/16448551/sigabrt_crash.txt)

### Expected Result

Should be no duplicate SIGABRT crash report.

### Actual Result

There are two reports for single crash - One report contains a legit kotlin stack trace, while the other is SIGABRT which includes a stack trace with coroutines machinery. The breadcrumbs in both reports are identical.

**Comment by buenaflor** [comment] 2024-08-01 07:39
hey, do you have ways to reproduce this?

**Comment by buenaflor** [comment] 2024-08-01 11:58
are you manipulating tags in `beforeSend` perhaps?

**Comment by alexander-ivanoff** [comment] 2024-08-05 07:00
> are you manipulating tags in `beforeSend` perhaps?

Yes, we did some filtration in `beforeSend` method. In latest release we removed this callback and sigabrt is gone.

**Comment by alexander-ivanoff** [comment] 2024-08-05 07:05
but we did not manipulate tags.  just filtered out `MetricKitDiskWriteDiagnostic` reports

`
        options.beforeSend = { event in
            guard !(event.exceptions?.contains(where: { $0.type == kMetricKitDiskWriteDiagnostic }) ?? false ) else {
                return nil
            }

            return event
        }
`

**Comment by buenaflor** [comment] 2024-08-05 08:34
Can you reproduce this duplicate report consistently when you crash?

**Comment by alexander-ivanoff** [comment] 2024-08-06 02:27
We can't after we removed `options.beforeSend` callback. But I'll make a build with this code is back and check.

**Comment by alexander-ivanoff** [comment] 2024-08-06 06:35
@buenaflor When `options.beforeSend` is returned - SIGABRT is returned too.

**Comment by alexander-ivanoff** [comment] 2024-08-08 03:21
@buenaflor Also, maybe it helps. That is how we initialize sdk

 I attached two of our classes used for sentry initialization (SentryService.swift and SentryInitializer.kt).

SentryService is called from AppDelegate.swift

```
func application(_ app: UIApplication,
                 didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    
    SentryService.initService()
    
    ...
    
    return true
}
```

[SentryInitializer.kt.txt](https://github.com/user-attachments/files/16537148/SentryInitializer.kt.txt)
[SentryService.swift.txt](https://github.com/user-attachments/files/16537149/SentryService.swift.txt)

**Comment by buenaflor** [comment] 2024-08-09 10:54
The swizzling is not needed anymore, read here about how to initialize with native options: https://docs.sentry.io/platforms/kotlin-multiplatform/initialization-strategies/#native-platform-options

The reason the duplicate report is still sent is because you are calling `SentrySDK.start` from the cocoa sdk, we add additional logic to ensure the duplicate report is not sent: https://github.com/getsentry/sentry-kotlin-multiplatform/blob/main/sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/SentryApple.kt#L7

So my suggestion: use `Sentry.initWithPlatformOptions` in the kmp layer if you want to use native options

**Comment by alexander-ivanoff** [comment] 2024-08-09 12:32
Great, thank you. 

We'll try new initialisation options.

**Comment by buenaflor** [comment] 2024-08-12 12:10
I'll close this issue for now, feel free to comment if something doesn't work or is still an issue

**Closed by buenaflor** 2024-08-12 12:10 UTC
Labels: Type: Bug, Platform: KMP
